### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by kptdobe** [kptdobe/helix-pmi#1]
- [x] general styling
- [x] gnav (copy + adapt from https://main--business-website--adobe.hlx3.page/blog/)
  - [x] Add missing PMI in gnav #16
  - [x] Category (first level) must be clickable #16 
  - [x] EN gnav
  - [x] language-toggle to mobile menu
- [x] footer (copy + adapt from https://main--business-website--adobe.hlx3.page/blog/) #3 
- [x] homepage
  - [x] 3x same "links" block (4 links to various pages, several options to display large if first one, link to a category)
- [x] article page #2 
- [x] category page (e.g. https://www.pmi.com/markets/italy/it/sostenibilita) #17 
  - [x] general styling
  - [x] article preview

- [x] re-organise index (move to IT folder and redirect / to /it/)
- [x] 3 columns ( [images+contnent](https://main--helix-pmi--kptdobe.hlx.live/it/chi-siamo/manufacturing-technology-bo) or [content](https://main--helix-pmi--kptdobe.hlx.live/it/chi-siamo/pmi) )
- [x] Video block (https://main--helix-pmi--kptdobe.hlx.live/it/sostenibilita/progetti-sostenibilita/cambiagesto)
- [x] Career page (https://main--helix-pmi--kptdobe.hlx.live/it/careers) - probably just cleanup - list of jobs = nice to have

### Footer
- [x] copyright string
- [x] privacy links styling
- [ ] mobile

### General
- [ ] breadcrump
- [ ] find other page "types" (news?, jobs?)
- [ ] gnav search (would need indexing of the articles for client side preview)
